### ISSUE TITLE
IndexError: out of range

### ISSUE THREAD

**Issue by kopiezzo** [drikqlis/SubSyncStarter#4]
Hi, im having this error while running post processing script in bazarr:

> 2020-02-24 17:07:14,248 - DEBUG: Error: None
2020-02-24 17:07:14,248 - DEBUG: Exit code: 126
2020-02-24 17:07:14,248 - ERROR: Sync failed - exception
Traceback (most recent call last):
  File "/path/to/my/SubSyncStarter.py", line 51, in <module>
    if "[+] done" in output_list[-1]:
IndexError: list index out of range

Why is this happening?

**Comment by drikqlis** [comment]
In the log file find the "Running command:" line and try to run this command manually in terminal. Show the output. Also make sure that you have SubSync installed and correct path set in config.ini

**Comment by dalaverd** [comment]
I am having the same error also while testing the command manually in terminal.
SubSync is installed correctly.

> mkdir: cannot create directory '/run/user/0': Permission denied
Traceback (most recent call last):
  File "/snap/subsync/10/bin/subsync", line 11, in <module>
    load_entry_point('subsync==0.15.0', 'gui_scripts', 'subsync')()
  File "/snap/subsync/10/lib/python3.5/site-packages/subsync/__main__.py", line 17, in subsync
    initConfig(args)
  File "/snap/subsync/10/lib/python3.5/site-packages/subsync/__main__.py", line 32, in initConfig
    loggercfg.init(level=args.logLevel, path=args.logFile)
  File "/snap/subsync/10/lib/python3.5/site-packages/subsync/loggercfg.py", line 40, in init
    filename=path)
  File "/snap/subsync/10/usr/lib/python3.5/logging/__init__.py", line 1744, in basicConfig
    h = FileHandler(filename, mode)
  File "/snap/subsync/10/usr/lib/python3.5/logging/__init__.py", line 1008, in __init__
    StreamHandler.__init__(self, self._open())
  File "/snap/subsync/10/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/SubSyncStarter/subsync.log'
2020-04-08 20:43:42,283 - DEBUG: Error: None
2020-04-08 20:43:42,284 - DEBUG: Exit code: 1
2020-04-08 20:43:42,299 - ERROR: Sync failed - exception
Traceback (most recent call last):
  File "/opt/SubSyncStarter/SubSyncStarter.py", line 51, in <module>
    if "[+] done" in output_list[-1]:
IndexError: list index out of range
Sync failed - exception

**Comment by dalaverd** [comment]
I was wondering if it was more of an issue with Subsync than your script.
I have tried to reinstall it with this method but there are no changes : https://github.com/sc0ty/subsync/issues/8#issuecomment-515588508

**Comment by drikqlis** [comment]
What is returned if you run subsync manually from terminal? Also try to create file /opt/SubSyncStarter/subsync.log and check if it is logging.

**Comment by dalaverd** [comment]
Actually, I am already doing it from terminal so I can have the complete log returned.
One of the first things that I did, is creating subsync.log with touch command inside SubSyncStarter folder (I am using Ubuntu 18.04 LTS). 

Also, I doubled-checked if permissions were ok on that folder (/opt/SubSyncStarter) :

![image](https://user-images.githubusercontent.com/4228254/78902813-47db2680-7a48-11ea-8570-3e245cd6ada1.png)

**Comment by drikqlis** [comment]
Ok, but the log is from SubSyncStarter, try to find in the log file line starting with "Running command:" which is running SubSync and run it and paste here the output.

**Comment by drikqlis** [comment]
I've rewritten this part, should be working better. I've also added blacklisting using bazarr API provided my pull request to add variables to post-processing would be merged.
